CREATE TABLE IF NOT EXISTS restaurants (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL UNIQUE,
    chef_special VARCHAR(255),
    owner VARCHAR(255) NOT NULL,
    tag VARCHAR(255),
    is_public BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id CHAR(36) NOT NULL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS active_sessions (
	id CHAR(36) NOT NULL PRIMARY KEY,
	token CHAR(36) NOT NULL UNIQUE,
	expiry DATETIME NOT NULL
);